### PR TITLE
Cycle debug

### LINKED ISSUE #85: PPG Cycle builder doesn't read back newly created cycle
Cd-cycle as an example. We created the cycle, changed the name in the text box, then clicked "Save Cycle Definition". It saved a cycle definition with the correct time lengths, but not with the correct PPG patterns (as viewed in the ODB).

Also, when I tried to load the cycle, it doesn't show any cycle steps.

(I fixed the PPG patterns by hand.)

### PR DESCRIPTION
**Pull request by katieannemills**
Fixes #85, and:
- requests new cycle name when any parameter is changed
- updates docs
- adds 'Save and Apply' option to match filter page
- supports fractional time units (down to whole ms - so 1.5s == 1500 ms)
- begins to fix loading bug - `PPGCodes` was incorrectly capitalized in some places as `PPGcodes`. Before we merge, several of the existing patterns in the ODB have this incorrect capitalization and need to be changed - @SmithJK, will this break other stuff or can I just go ahead and change them?

### CODE REVIEW

**Comment by katieannemills** [comment]
hmm - on second thought, the docs say `PPGcodes`, not `PPGCodes`, so maybe we should go that way instead. Same question though - ok to update the ODB?

**Comment by SmithJK** [comment]
Where are these difference in the ODB?

**Comment by katieannemills** [comment]
@SmithJK For example, in the ODB, I want to change `/PPG/Cycles/Cd-cycle/PPGCodes` to `/PPG/Cycles/Cd-cycle/PPGcodes` (capitalization difference `PPGCodes` -> `PPGcodes`), and all corresponding changes under `/PPG/Cycles/*`.

**Comment by SmithJK** [comment]
After looking at the frontend code, I think this is a good change to go ahead and make. We haven't tested the Cd-cycles yet, but I suspect they wouldn't work with this capitalization.

**Comment by katieannemills** [comment]
ok, that ought to do it - I updated the ODB as mentioned, and everything should be consistent now, let me know any concerns.

**Pull request merged**
